name: Terraform Deployment

on:
  push:
    branches:
      - main
      - dev
      - uat
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: ./terraform

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            if [[ "${GITHUB_REF##*/}" == "main" ]]; then
              echo "ENV=prod" >> $GITHUB_ENV
            elif [[ "${GITHUB_REF##*/}" == "uat" ]]; then
              echo "ENV=uat" >> $GITHUB_ENV
            else
              echo "ENV=dev" >> $GITHUB_ENV
            fi
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Workspace
        run: terraform workspace select $ENV || terraform workspace new $ENV

      - name: Plan
        run: terraform plan -var="environment=$ENV"

      - name: Apply
        run: terraform apply -auto-approve
